/* =====================================================================
   PINK WORLD — PRODUCT CATALOG (default / offline catalog)
   -----------------------------------------------------------------
   Each product's "sizes" field is a list of { size, stock } objects —
   this powers automatic "Sold Out" labels and per-size availability
   across the site. Manage all of this using admin.html.
   ===================================================================== */

const PRODUCTS = [
  // ---------------- SAREES ----------------
  { id: "P001", name: "Pink Floral Silk Saree", category: "sarees", price: 2499, mrp: 2999, image: "images/cat-sarees.jpg", badge: "Sale", sizes: [{ size: "Free Size", stock: 8 }], description: "Elegant pink silk saree with delicate floral zari weave, comes with matching blouse piece." },
  { id: "P002", name: "Golden Zari Border Silk Saree", category: "sarees", price: 3199, mrp: null, image: "images/cat-sarees.jpg", badge: "New", sizes: [{ size: "Free Size", stock: 5 }], description: "Rich silk saree with a broad golden zari border, perfect for weddings and festive occasions." },
  { id: "P003", name: "Pastel Lavender Organza Saree", category: "sarees", price: 1899, mrp: 2199, image: "images/cat-sarees.jpg", badge: "Sale", sizes: [{ size: "Free Size", stock: 0 }], description: "Lightweight organza saree in soft lavender with all-over floral print, ideal for daytime events." },
  { id: "P004", name: "Cream Embroidered Saree with Blouse", category: "sarees", price: 2799, mrp: null, image: "images/cat-sarees.jpg", badge: "", sizes: [{ size: "Free Size", stock: 6 }], description: "Cream base saree with fine thread embroidery and a designer stitched blouse piece." },
  { id: "P005", name: "Peach Kanjivaram-Style Saree", category: "sarees", price: 3499, mrp: 3999, image: "images/cat-sarees.jpg", badge: "Bestseller", sizes: [{ size: "Free Size", stock: 10 }], description: "Traditional Kanjivaram-style weave in soft peach with contrast pallu." },
  { id: "P006", name: "Magenta Banarasi Silk Saree", category: "sarees", price: 3999, mrp: null, image: "images/cat-sarees.jpg", badge: "New", sizes: [{ size: "Free Size", stock: 3 }], description: "Vibrant magenta Banarasi silk saree with intricate golden motifs throughout." },

  // ---------------- KURTIS & SUITS ----------------
  { id: "P007", name: "White Floral Print Cotton Kurti Set", category: "kurtis", price: 899, mrp: null, image: "images/cat-kurtis.jpg", badge: "", sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 8 }, { size: "L", stock: 6 }, { size: "XL", stock: 0 }], description: "3-piece cotton kurti set with pink floral print, includes bottom and dupatta." },
  { id: "P008", name: "Yellow Block Print Kurti with Dupatta", category: "kurtis", price: 949, mrp: 1099, image: "images/cat-kurtis.jpg", badge: "Sale", sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 4 }, { size: "L", stock: 0 }, { size: "XL", stock: 2 }], description: "Sunny yellow block-printed kurti set, breathable cotton fabric for everyday wear." },
  { id: "P009", name: "Pink Floral Embroidered Kurti Set", category: "kurtis", price: 1099, mrp: null, image: "images/cat-kurtis.jpg", badge: "Bestseller", sizes: [{ size: "S", stock: 3 }, { size: "M", stock: 5 }, { size: "L", stock: 7 }, { size: "XL", stock: 2 }, { size: "XXL", stock: 0 }], description: "Rose pink kurti with floral embroidery on the neckline, paired with matching bottoms." },
  { id: "P010", name: "Mint Green Embellished Kurti Set", category: "kurtis", price: 1299, mrp: 1499, image: "images/cat-kurtis.jpg", badge: "Sale", sizes: [{ size: "S", stock: 0 }, { size: "M", stock: 0 }, { size: "L", stock: 0 }, { size: "XL", stock: 0 }], description: "Festive mint green kurti with sequin and thread embellishment, comes with dupatta." },
  { id: "P011", name: "Navy Blue Printed Kurti Set", category: "kurtis", price: 999, mrp: null, image: "images/cat-kurtis.jpg", badge: "", sizes: [{ size: "S", stock: 8 }, { size: "M", stock: 6 }, { size: "L", stock: 4 }, { size: "XL", stock: 3 }], description: "Deep navy kurti set with intricate ethnic print, ideal for office and casual outings." },
  { id: "P012", name: "Cream Floral Kurti Pyjama Set", category: "kurtis", price: 1049, mrp: null, image: "images/cat-kurtis.jpg", badge: "New", sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 7 }, { size: "L", stock: 9 }, { size: "XL", stock: 2 }], description: "Comfortable cream kurti with pink floral embroidery, paired with matching pyjama." },
  { id: "P013", name: "Lavender Embroidered Kurti Set", category: "kurtis", price: 1149, mrp: 1299, image: "images/cat-kurtis.jpg", badge: "Sale", sizes: [{ size: "S", stock: 4 }, { size: "M", stock: 6 }, { size: "L", stock: 3 }, { size: "XL", stock: 5 }], description: "Soft lavender kurti with white floral embroidery and lace detailing on sleeves." },
  { id: "P014", name: "Mustard Floral Kurti Set", category: "kurtis", price: 999, mrp: null, image: "images/cat-kurtis.jpg", badge: "", sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 8 }, { size: "L", stock: 5 }, { size: "XL", stock: 3 }, { size: "XXL", stock: 2 }], description: "Mustard yellow kurti set with pink floral motifs, includes matching dupatta." },

  // ---------------- WESTERN WEAR ----------------
  { id: "P015", name: "Blue Floral Peplum Top", category: "western", price: 599, mrp: null, image: "images/cat-western.jpg", badge: "New", sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 3 }, { size: "L", stock: 0 }], description: "Casual peplum-style top with blue floral print, pairs well with jeans or shorts." },
  { id: "P016", name: "Sage Green Ruffle Top", category: "western", price: 549, mrp: 649, image: "images/cat-western.jpg", badge: "Sale", sizes: [{ size: "S", stock: 4 }, { size: "M", stock: 6 }, { size: "L", stock: 2 }], description: "One-shoulder ruffle top in sage green, perfect for a summer evening out." },
  { id: "P017", name: "Ivory Embroidered Blouse", category: "western", price: 699, mrp: null, image: "images/cat-western.jpg", badge: "", sizes: [{ size: "S", stock: 3 }, { size: "M", stock: 5 }, { size: "L", stock: 4 }, { size: "XL", stock: 2 }], description: "Ivory blouse with delicate floral embroidery and tie-up neckline detail." },
  { id: "P018", name: "Dusty Pink Smocked Top", category: "western", price: 649, mrp: null, image: "images/cat-western.jpg", badge: "Bestseller", sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 4 }, { size: "L", stock: 3 }], description: "Smocked bodice top in dusty pink with adjustable tie straps." },
  { id: "P019", name: "Blue Floral Puff Sleeve Dress", category: "western", price: 1199, mrp: 1399, image: "images/cat-western.jpg", badge: "Sale", sizes: [{ size: "S", stock: 2 }, { size: "M", stock: 0 }, { size: "L", stock: 1 }], description: "Flowy mini dress with puff sleeves and all-over blue floral print." },
  { id: "P020", name: "Pink Floral Tiered Dress", category: "western", price: 1299, mrp: null, image: "images/cat-western.jpg", badge: "New", sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 4 }, { size: "L", stock: 3 }], description: "Tiered midi dress in soft pink floral print, smocked waist for a flattering fit." },
  { id: "P021", name: "Striped Ribbed Tank Top", category: "western", price: 399, mrp: null, image: "images/cat-western.jpg", badge: "", sizes: [{ size: "S", stock: 8 }, { size: "M", stock: 6 }, { size: "L", stock: 5 }, { size: "XL", stock: 4 }], description: "Classic black and white striped ribbed tank, a wardrobe staple." },
  { id: "P022", name: "High-Rise Denim Shorts", category: "western", price: 799, mrp: 899, image: "images/cat-western.jpg", badge: "Sale", sizes: [{ size: "28", stock: 5 }, { size: "30", stock: 6 }, { size: "32", stock: 4 }, { size: "34", stock: 0 }], description: "Distressed high-rise denim shorts with raw hem finish." },
  { id: "P023", name: "Classic Blue Straight Jeans", category: "western", price: 1399, mrp: null, image: "images/cat-western.jpg", badge: "", sizes: [{ size: "28", stock: 4 }, { size: "30", stock: 6 }, { size: "32", stock: 8 }, { size: "34", stock: 5 }, { size: "36", stock: 3 }], description: "Light-wash straight fit jeans, comfortable stretch denim." },
  { id: "P024", name: "Black Denim Jeans", category: "western", price: 1399, mrp: null, image: "images/cat-western.jpg", badge: "Bestseller", sizes: [{ size: "28", stock: 3 }, { size: "30", stock: 5 }, { size: "32", stock: 0 }, { size: "34", stock: 4 }, { size: "36", stock: 2 }], description: "Versatile black denim jeans that pair with everything." },

  // ---------------- MEN'S COLLECTIONS ----------------
  { id: "P025", name: "Sky Blue Oxford Casual Shirt", category: "mens", price: 899, mrp: null, image: "images/cat-mens.jpg", badge: "New", sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 8 }, { size: "L", stock: 7 }, { size: "XL", stock: 5 }, { size: "XXL", stock: 2 }], description: "Breathable sky blue oxford cotton shirt with a classic button-down collar." },
  { id: "P026", name: "Navy Pinstripe Formal Shirt", category: "mens", price: 999, mrp: 1199, image: "images/cat-mens.jpg", badge: "Sale", sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 6 }, { size: "L", stock: 4 }, { size: "XL", stock: 3 }, { size: "XXL", stock: 0 }], description: "Sharp navy pinstripe shirt, tailored fit, perfect for office wear." },
  { id: "P027", name: "Forest Green Tipped Polo", category: "mens", price: 799, mrp: null, image: "images/cat-mens.jpg", badge: "Bestseller", sizes: [{ size: "S", stock: 7 }, { size: "M", stock: 9 }, { size: "L", stock: 6 }, { size: "XL", stock: 4 }], description: "Classic pique polo in forest green with contrast tipped collar." },
  { id: "P028", name: "Maroon Tipped Collar Polo", category: "mens", price: 799, mrp: 899, image: "images/cat-mens.jpg", badge: "Sale", sizes: [{ size: "S", stock: 4 }, { size: "M", stock: 5 }, { size: "L", stock: 3 }, { size: "XL", stock: 2 }], description: "Rich maroon polo shirt with white tipping detail, soft cotton pique fabric." },
  { id: "P029", name: "Striped Rugby Polo", category: "mens", price: 849, mrp: null, image: "images/cat-mens.jpg", badge: "New", sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 7 }, { size: "L", stock: 5 }, { size: "XL", stock: 3 }], description: "Sporty striped polo with contrast chest panel, great for casual outings." },
  { id: "P030", name: "Khaki Chino Trousers", category: "mens", price: 1099, mrp: null, image: "images/cat-mens.jpg", badge: "", sizes: [{ size: "30", stock: 5 }, { size: "32", stock: 7 }, { size: "34", stock: 6 }, { size: "36", stock: 4 }, { size: "38", stock: 2 }], description: "Comfortable slim-fit khaki chinos, versatile for work or weekends." },
  { id: "P031", name: "Olive Green Chino Pants", category: "mens", price: 1099, mrp: 1299, image: "images/cat-mens.jpg", badge: "Sale", sizes: [{ size: "30", stock: 4 }, { size: "32", stock: 6 }, { size: "34", stock: 0 }, { size: "36", stock: 3 }, { size: "38", stock: 2 }], description: "Olive green chinos with a tailored fit and durable cotton twill." },
  { id: "P032", name: "Charcoal Grey Formal Trousers", category: "mens", price: 1199, mrp: null, image: "images/cat-mens.jpg", badge: "Bestseller", sizes: [{ size: "30", stock: 3 }, { size: "32", stock: 5 }, { size: "34", stock: 4 }, { size: "36", stock: 2 }, { size: "38", stock: 0 }], description: "Sharp charcoal grey trousers, perfect for formal and office occasions." },

  // ---------------- INTIMATE & INNERWEAR ----------------
  { id: "P033", name: "Ivory Lace Trim T-Shirt Bra", category: "intimate", price: 499, mrp: null, image: "images/cat-intimate.jpg", badge: "New", sizes: [{ size: "32B", stock: 8 }, { size: "34B", stock: 6 }, { size: "36B", stock: 5 }, { size: "38B", stock: 3 }], description: "Everyday ivory t-shirt bra with delicate lace trim and full coverage." },
  { id: "P034", name: "Dusty Rose Padded Bra", category: "intimate", price: 549, mrp: 649, image: "images/cat-intimate.jpg", badge: "Sale", sizes: [{ size: "32B", stock: 5 }, { size: "34B", stock: 0 }, { size: "36B", stock: 4 }, { size: "38B", stock: 2 }], description: "Soft padded bra in dusty rose with adjustable straps for all-day comfort." },
  { id: "P035", name: "Mauve Lace Bralette", category: "intimate", price: 449, mrp: null, image: "images/cat-intimate.jpg", badge: "Bestseller", sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 8 }, { size: "L", stock: 5 }], description: "Wire-free mauve lace bralette, soft and breathable for everyday comfort." },
  { id: "P036", name: "Pastel Camisole Set (3-Pack)", category: "intimate", price: 699, mrp: 799, image: "images/cat-intimate.jpg", badge: "Sale", sizes: [{ size: "S", stock: 4 }, { size: "M", stock: 6 }, { size: "L", stock: 5 }, { size: "XL", stock: 3 }], description: "Set of 3 lace-trimmed camisoles in sage, lavender, and blush pastel shades." },
  { id: "P037", name: "Cotton Rib Briefs (2-Pack)", category: "intimate", price: 349, mrp: null, image: "images/cat-intimate.jpg", badge: "New", sizes: [{ size: "S", stock: 10 }, { size: "M", stock: 8 }, { size: "L", stock: 6 }, { size: "XL", stock: 4 }], description: "Soft cotton rib briefs with lace edge detail, breathable everyday comfort." },
  { id: "P038", name: "Floral Print Cotton Pyjama Set", category: "intimate", price: 899, mrp: null, image: "images/cat-intimate.jpg", badge: "", sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 7 }, { size: "L", stock: 4 }, { size: "XL", stock: 0 }], description: "Cozy floral print cotton shirt and pyjama set, perfect for relaxed nights in." },
  { id: "P039", name: "Rosewood Lace Bralette", category: "intimate", price: 479, mrp: 549, image: "images/cat-intimate.jpg", badge: "Sale", sizes: [{ size: "S", stock: 3 }, { size: "M", stock: 5 }, { size: "L", stock: 0 }], description: "Delicate rosewood lace bralette with scalloped edges, wire-free comfort." },
  { id: "P040", name: "Satin Piped Nightwear Set", category: "intimate", price: 949, mrp: null, image: "images/cat-intimate.jpg", badge: "Bestseller", sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 4 }, { size: "L", stock: 3 }, { size: "XL", stock: 2 }], description: "Elegant blush pink nightwear set with satin piping, soft breathable fabric." }
];

const CATEGORIES = [
  { id: "sarees", name: "Sarees", image: "images/cat-sarees.jpg", description: "Silk, Banarasi & festive sarees" },
  { id: "kurtis", name: "Kurtis & Suits", image: "images/cat-kurtis.jpg", description: "Cotton & embroidered kurti sets" },
  { id: "western", name: "Western Wear", image: "images/cat-western.jpg", description: "Tops, dresses, jeans & more" },
  { id: "mens", name: "Men's Collections", image: "images/cat-mens.jpg", description: "Shirts, polos & trousers" },
  { id: "intimate", name: "Intimate & Innerwear", image: "images/cat-intimate.jpg", description: "Bras, briefs & nightwear" }
];
